// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/schools": {
            "get": {
                "description": "학교 목록을 키워드를 바탕으로 조회한다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "학교 목록 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "검색 키워드",
                        "name": "keyword",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.School"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/v1/schools/meals": {
            "get": {
                "description": "특정 학교의 월별 식단표를 제공한다",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "식단표 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "시도교육청코드",
                        "name": "eduOfficeCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "학교 행정표준코드",
                        "name": "schoolCode",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "요청하려는 연도 (YYYY)",
                        "name": "year",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "요청하려는 달 (MM)",
                        "name": "month",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/controller.CommonResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/service.Meal"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controller.CommonResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "isError": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "service.Meal": {
            "type": "object",
            "properties": {
                "calInfo": {
                    "type": "string"
                },
                "dishName": {
                    "type": "string"
                },
                "loadDtm": {
                    "type": "string"
                },
                "mlsvFgr": {
                    "type": "number"
                },
                "mlsvFromYmd": {
                    "type": "string"
                },
                "mlsvToYmd": {
                    "type": "string"
                },
                "mlsvYmd": {
                    "type": "string"
                },
                "mmealScCode": {
                    "type": "string"
                },
                "mmealScNm": {
                    "type": "string"
                },
                "ntrInfo": {
                    "type": "string"
                },
                "orplcInfo": {
                    "type": "string"
                },
                "schoolAdminCode": {
                    "type": "string"
                },
                "schoolName": {
                    "type": "string"
                },
                "sidoEduOfficeCode": {
                    "type": "string"
                },
                "sidoEduOfficeName": {
                    "type": "string"
                }
            }
        },
        "service.School": {
            "type": "object",
            "properties": {
                "adminStandardCode": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "roadAddress": {
                    "type": "string"
                },
                "roadDetailAddress": {
                    "type": "string"
                },
                "schoolName": {
                    "type": "string"
                },
                "sidoEduOfficeCode": {
                    "type": "string"
                },
                "sidoEduOfficeName": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "AfterHee API",
	Description:      "희그 그 이후 API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
