basePath: /
definitions:
  controller.CommonResponse:
    properties:
      data: {}
      isError:
        type: boolean
      message:
        type: string
    type: object
  controller.SuggestMenuRequest:
    properties:
      category:
        type: string
      skipMenus:
        items:
          type: string
        type: array
    type: object
  controller.SuggestTestRequest:
    properties:
      prompt:
        type: string
    type: object
  service.Meal:
    properties:
      calInfo:
        type: string
      dishNames:
        items:
          type: string
        type: array
      loadDtm:
        type: string
      mlsvFgr:
        type: number
      mlsvFromYmd:
        type: string
      mlsvToYmd:
        type: string
      mlsvYmd:
        type: string
      mmealScCode:
        type: string
      mmealScNm:
        type: string
      ntrInfo:
        type: string
      orplcInfo:
        type: string
      schoolAdminCode:
        type: string
      schoolName:
        type: string
      sidoEduOfficeCode:
        type: string
      sidoEduOfficeName:
        type: string
    type: object
  service.School:
    properties:
      adminStandardCode:
        type: string
      id:
        type: integer
      roadAddress:
        type: string
      roadDetailAddress:
        type: string
      schoolName:
        type: string
      sidoEduOfficeCode:
        type: string
      sidoEduOfficeName:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 희그 그 이후 API
  title: AfterHee API
  version: "1.0"
paths:
  /api/v1/healthcheck:
    get:
      description: 항상 HTTP 200 코드를 반환한다. 서버 상태를 체크하는 용도로 사용한다.
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 헬스 체크
  /api/v1/schools:
    get:
      consumes:
      - application/json
      description: 학교 목록을 키워드를 바탕으로 조회한다
      parameters:
      - description: 검색 키워드
        in: query
        name: keyword
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.School'
                  type: array
              type: object
      summary: 학교 목록 조회
  /api/v1/schools/meals:
    get:
      consumes:
      - application/json
      description: 특정 학교의 월별 식단표를 제공한다
      parameters:
      - description: 시도교육청코드
        in: query
        name: eduOfficeCode
        required: true
        type: string
      - description: 학교 행정표준코드
        in: query
        name: schoolCode
        required: true
        type: string
      - description: 요청하려는 시작 일자 (YYYY-MM-DD)
        in: query
        name: from
        required: true
        type: string
      - description: 요청하려는 종료 일자 (YYYY-MM-DD)
        in: query
        name: to
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Meal'
                  type: array
              type: object
      summary: 식단표 조회
  /api/v1/suggest:
    post:
      consumes:
      - application/json
      description: '메뉴를 제안한다. category는 다음만 허용한다: "한식", "일식", "중식", "양식", "아시안", "세계음식",
        "찜", "국물", "볶음", "밥", "면", "빵", "해물", "고기", "야채", "빠른 식사", "디저트",'
      parameters:
      - description: request suggest menu body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.SuggestMenuRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.SuggestMenuRequest'
              type: object
      summary: 메뉴 제안
  /api/v1/test/suggest:
    post:
      consumes:
      - application/json
      description: 프롬프트로 LLM에 요청을 보낸다.
      parameters:
      - description: request suggest menu body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.SuggestTestRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controller.CommonResponse'
            - properties:
                data:
                  $ref: '#/definitions/controller.SuggestMenuRequest'
              type: object
      summary: 매뉴얼 프롬프트 테스팅
swagger: "2.0"
